### ISSUE TITLE
Feature Request: Style Settings Plugin

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/shimmering-focus#2]
Integrate with [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings).
Options would be:
- Turn off Pandoc Citation Highlighting
- Change Highlight Colors
- re-enable hidden elements (titlebar, headerbar, ribbons, etc.)

Please react / comment if you would like to see this implemented, so I can see whether there is even demand for it. Thanks!

**Comment by planktic** [comment]
Yes, please! I would love to see this!!

**Comment by firinael** [comment]
Please allow for the changing of fonts and of the colour of some elements.

For example, the white border on modals is something that put me off the theme.

EDIT: also please allow for changing of the toggle pills, I hate those square ones lol.

**Comment by ms3056** [comment]
YES Please! 

- Fonts Families
- Colors
- Hidden items
- Header Font Sizes
- Additional admonition codes (perhaps this is more for the style itself, not the plugin)

**Comment by hieu6** [comment]
yes please! 

+1 to font family, header sizes...

or the "adjust all the things" settings style chetachi adds in yin yang 👀

**Comment by marti-h** [comment]
please. unhide titlebar, sidebar. would be great!

**Comment by chrisgrieser** [comment]
Thanks everyone for all the feedback. Since there is actually quite a lot demand for it, I added support for the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/).

Update to [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4) (either by downloading it manually or via the Community Theme browser), install the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/), and you will be able to:
- re-enable the titlebar
- re-enable the ribbons (the thin vertical bars to the far left and right)
- change all heading font sizes
- change (some) font-families
- choose between round or square-ish checkboxes

This took a bit time, since re-enabling titlebar and/or ribbon made some harmonization with the rest of the UI necessary, in addition I wanted to add the general readability improvements (increased contrast, etc.) to the ribbon/titlebar as well.

--- 

**Changing the main font** (iA Writer Quattro) is a bit more tricky, since it consists of several font files and also has custom styling done by me. I'll try to figure it out for the next update.

**Changing colors** is also on my to do list for the next update, colors are also a bit tricky since Shimmering Focus uses several tones of its two main colors, and I will have to do some re-factoring of the CSS colors in HSL before colors can be changed in a user friendly way.

"Adjusting all the things" will likely not happen for a while, since it takes quite a bit of time^^ But you can name the features you wish to change, and I'll try to implement to most wished settings.

**Comment by chrisgrieser** [comment]
@ms3056 
> * Additional admonition codes (perhaps this is more for the style itself, not the plugin)

Well, what I implemented is more of a paupers version of Admonitions by repurposing H6 Headers. I do not think that more Admonitions are possible solely through CSS. If you would like to have more admonition styles, you will have to go for the [Admonition Plugin itself](https://github.com/valentine195/obsidian-admonition).

**Comment by chrisgrieser** [comment]
@firinael 
> For example, the white border on modals is something that put me off the theme.

yeah, to be honest, they were annoying me, too, after a bit, so I removed them in the last update. 😝 

> EDIT: also please allow for changing of the toggle pills, I hate those square ones lol.

done in 1.4, see above 🙂 

> EDIT2: also also, line width!

You can already change the line width via `Settings ➞ Editor ➞ Readable Line Length`

**Comment by marti-h** [comment]
Hello 

Thanks for the changes. Especially the reappearance of the nav bar. 

I updated my copy of your theme. A couple of things where changed and I am unable to change back. 

1. bold text is no longer bold
2. the font of the headers are not the same

marti

**Comment by chrisgrieser** [comment]
> bold text is no longer bold

Sorry, made a small typo with the 1.4 release. Is fixed now, thanks for letting me know.

> the font of the headers are not the same

In fact, they are the same font – what you probably mean is the alternation between italic and non-italic heading levels. It's one of the minor new features of 1.4 and is intended to make it easier to distinguish heading levels. I just added a Style Settings option to turn that feature off, if you prefer normal headings.

Both are added as hotfixes to the [1.4 release](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4). Simply redownload  from the GitHub releases or update the Community Theme Browser.

**Comment by marti-h** [comment]
Thank you. Much appreciated for the changes. 

Managed to sort the header myself.

**Comment by chrisgrieser** [comment]
Just a short info for everyone: there was unfortunately yet another small bug that let to settings being reseted after very Obsidian restart.

Has been fixed in [release 1.4.3](https://github.com/chrisgrieser/shimmering-focus/releases), which you can download here at Github or by updating in the Community Theme Browser from within Obsidian.

Sorry for the inconvenience, it's still my first css project. 😟

**Comment by cashew90** [comment]
Just a quick question: At the moment, the file's title only appears when hovering over it, which means that it is not visible when I type it. Is there a possibility to either make it an option in style settings to re-enable it, or to at least show the title when it is written? 

Thank you! 😊

**Comment by chrisgrieser** [comment]
> Just a quick question: At the moment, the file's title only appears when hovering over it, which means that it is not visible when I type it. Is there a possibility to either make it an option in style settings to re-enable it, or to at least show the title when it is written?

Hmm, I will have to look into how to do that, I'll write it down for the next release

**Comment by ms3056** [comment]
- Convert - to a circle in edit mode
- Change color and size of # in headers 
- Add an underline for H1 headers 

![image](https://user-images.githubusercontent.com/23712700/132604627-49717b5b-7315-4282-ae47-9aa28bc01ae2.png)

- remove the --- from the horizontal line in edit mode
![image](https://user-images.githubusercontent.com/23712700/132604717-72a5229b-d934-4477-a853-a913a855ec65.png)

**Comment by marti-h** [comment]
Hey

Great work on the theme. One of my favourite. 

Just answer request - is to make the emoji not so squished in the preview mode. 
![Screenshot 2021-09-08 214213](https://user-images.githubusercontent.com/90190871/132635741-6e884fb2-216a-4521-8fa6-d4b928691847.png)

**Comment by chrisgrieser** [comment]
I figured out how to change the main font – the solution was actually easier than I expected.

As before, [download release 1.5 from GitHub](https://github.com/chrisgrieser/shimmering-focus/releases/latest) or update via the community theme browser, then you will have an option to change the main theme of with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
@marti-h 
When I tried to reproduce your issue, emojis look fine in both editor and preview mode. From what I can tell from your screenshot, it looks like you use a plugin as well as a different heading font. Maybe one of them causes the issue?

<img width="395" alt="Screenshot 2021-09-09 13 49 56" src="https://user-images.githubusercontent.com/73286100/132680687-b9b7651e-0e12-468e-8e72-31ba743e5fa6.png">
<img width="382" alt="Screenshot 2021-09-09 13 49 43" src="https://user-images.githubusercontent.com/73286100/132680690-b158f3ec-7c62-4cf5-ac63-9e2e7898a451.png">

**Comment by ReaderGuy42** [comment]
Hi, it would be awesome if the header could be re-enabled permanently, not just while hovering, as mentionted by someone above.

I love the multiple highlighting colors! 
Thanks :)

**Comment by chrisgrieser** [comment]
Alright, [with release 1.8](https://github.com/chrisgrieser/shimmering-focus/releases/latest), you can use the Style Settings plugin to permanently re-enable the header bar 🙂 
cc  @cashew90 @ReaderGuy42

**Comment by cashew90** [comment]
Uh nice, thank you!

**Comment by ReaderGuy42** [comment]
Hi, thanks for that update in 1.8! However, it seems that in this new version all quote blocks have the background color that previously only the currently active parargraph had. Was that intentional? I don't think that was there in  the previous version.

**Comment by chrisgrieser** [comment]
@ReaderGuy42 
That was a small change I made to blockquote in one of the prior versions, yes!  It was meant to make blockquotes more distinguishable from the maintext without them being having a light-grey font-color. (which I did not want due to low contrast/ readability).

However, you are when a blockquote is *also* the active line, the highlighting was not applied properly. I have fixed that in[ release 1.8.1](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.8.1). Thanks for letting me know!

**Comment by ReaderGuy42** [comment]
@chrisgrieser 

Thanks for replying so quickly! Unfortunately it doesn't seem to have changed anything. The blockquotes are still that same gray, and when marking a line the latter is still not visible.

**Comment by chrisgrieser** [comment]
ah, right, forgot to mention: What I fixed was the color of the of blockquotes when they are also the active line.

The fact that marking text does not properly show the selection color actually isn't a bug of this theme but a bug on Obsidian's side: https://forum.obsidian.md/t/inline-code-occludes-text-selection-and-vim-cursor/11552

**Comment by chrisgrieser** [comment]
Oh well, in the very same forum thread, someone also posted a solution. To the problem :)

I applied it to the theme, [release 1.8.2](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.8.2) should fix the issue then.

**Comment by ReaderGuy42** [comment]
Awesome, thanks!

**Comment by ReaderGuy42** [comment]
Hi again, I have something else: 

I've noticed that when the Search field is open (Ctrl + F) on the bottom of the page, when you try to press "previous result", the field with the word count etc. pops in, making it impossible to press the "previous result" button. 

Thanks :)

**Comment by chrisgrieser** [comment]
ah, good find, i use the search to rarely that I didn't notice. [Fixed in release 1.12](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.12).

**Comment by ReaderGuy42** [comment]
Fantastic, thank you! I appreciate that you fix the bugs so quickly :)

**Comment by chrisgrieser** [comment]
well, let's say I got a deadline next week and I am procrastinating :P

otherwise, I'll close this issue, as it isn't really about the Style Settings plugin anymore. When new issues come up, feel free open a new issue.

Also anyone who still has wishes for the style settings plugin, please create a new issue for them, so users can upvote individual wishes.

**Comment by BradyRosino** [comment]
> Hey
> 
> Great work on the theme. One of my favourite.
> 
> Just answer request - is to make the emoji not so squished in the preview mode. ![image](https://user-images.githubusercontent.com/90190871/132636062-3f37b54f-77c4-4ec1-ae63-6937905d314b.png)

I was having issues with this as well where emojis were being treated as images and preview was getting all messed up. Found my issue.

Turns out (for me) it was the Emoji Toolbar plugin. This plugin has an option, set to enabled by default, to replace emojis with Twitter-styled emoji. It does this by replacing the unicode emoji with img tags of the Twitter images.

Turning off this option in the Emoji Toolbar plugin _then restarting Obsidian_ fixed my issue.

Thank you @chrisgrieser  for the amazing work here!

**Comment by cashew90** [comment]
Is it possible to change the toggle switches' size in edit mode? It all looks good in reading mode.

<img width="140" alt="CleanShot 2022-01-05 at 12 37 56@2x" src="https://user-images.githubusercontent.com/20352339/148212235-64370a23-5b5a-4021-bffa-039f984f9571.png">

**Comment by chrisgrieser** [comment]
That's an issue that occurs with the insider release, since it changes the way CSS for collapse indicators is handled: https://discord.com/channels/686053708261228577/702656734631821413/927809412205256725

It's a bit annoying since changing the styling would also affect users on the public release. for now, I have simply reverted the size back, so people on Insider can use it, with the public release I'll do proper styling since then it would affect everyone the same way. Update the theme, where it will be fixed

**Comment by cashew90** [comment]
Thank you for the quick fix!
